### PR TITLE
Correcting use_legacy_dirichlet_bc and use_legacy_material_output in BlackBearApp

### LINKED ISSUE #177: Convergence issue of 2D-RZ_finiteStrain_resid.i from tensor mechanics
## Bug Description
blackbear-opt cause problem in converging some test from tensormechanics. 

## Steps to Reproduce
Addition of leagecy dirichlet BC and legacy material output in BlackBearApp.
## Impact
I could not to develop an axisymmetric model that runs well in BlackBear.

### PR DESCRIPTION
**Pull request by jain651**
This PR adds use_legacy_dirichlet_bc and use_legacy_material_output parameters in the BlackBearApp.C so that BlackBearApp runs the input file in the same way as TensorMechanics module. One example of such file is "moose/modules/tensor_mechanics/test/tests/2D_geometries/2D-RZ_finiteStrain_resid.i"
close #177

### CODE REVIEW

**Comment by jain651** [comment]
@bwspenc Could you please review it?

**Comment by bwspenc** [comment]
A few things:
1) It looks like you did not open an issue for this. You can't point to this PR for the issue.
2) Once you create the issue, you need to put 'closes #issue_number' in your commit as well as at the top of the first comment on this PR
3) Please squash your commits into a single commit. (git rebase -i HEAD~4)
4) What's the story on commenting out that Cartesian output line?
5) Why did an exodus file need to be re-golded? I assume that's because it slightly changed how the problem ran, but you should make a note of that somewhere.

**Comment by jain651** [comment]
I have created a new issue (#177) and submitted a PR for that.

"What's the story on commenting out that Cartesian output line?"
I was having some issue posting the PR. But now it seems fine.

**Comment by jain651** [comment]
Please see my response:
1. It looks like you did not open an issue for this. You can't point to this PR for the issue.
  - I have created a new issue (#177) and submitted a PR for that.
2. Once you create the issue, you need to put 'closes #issue_number' in your commit as well as at the top of the first comment on this PR
  - I also did this in #177.
3. Please squash your commits into a single commit. (git rebase -i HEAD~4)
  - I will do that one I resolve problems with Civet errors.
4. What's the story on commenting out that Cartesian output line?
  - In civet, I am getting error in the build process. I am not sure how to resolve that.
5. Why did an exodus file need to be re-golded? I assume that's because it slightly changed how the problem ran, but you should make a note of that somewhere.
  - The difference in the two gold file exceeds tolerance in Civet test. I am not sure what I need to do with that because I am changing anything relevant to that which can affect the difference in two gold files.

File: src/main.C [hunk 1]
```diff
@@ -33,7 +33,7 @@ main(int argc, char * argv[])
   BlackBearTestApp::registerApps();
 
   // register inelastic strain
-  TensorMechanicsActionBase::addCartesianComponentOutput("inelastic_strain");
```
Comment (bwspenc) [inline src/main.C:36]: I think you don't want this change, right?

Comment (jain651) [reply src/main.C:36]: No, I don't want these changes.  I will commit my changes again to include this one and one for the input file for the "sulfide_attack.i"

Comment (jain651) [reply src/main.C:36]: Ben, It seems like I still need to change several other files in order to build Blackbear in this branch. I am not sure why but please do not merge it.
