### PR TITLE
Correct convection term 

### LINKED ISSUE #125: Incorrect sign for convection term in heat equation
## Bug Description
The sign for the convection term associated with heat transfer in concrete is incorrect.

## Steps to Reproduce
Compare the model to the reference paper. 

## Impact
Would require re-golding of various tests.

### PR DESCRIPTION
**Pull request by SudiptaBiswas**
- Corrects the sign for the convection terms
- Updates associated tests

Closes #125

### CODE REVIEW

File: src/kernels/ConcreteThermalConvection.C [hunk 1]
```diff
@@ -21,27 +21,41 @@ InputParameters
...
   // return -_specific_heat_water[_qp]*_darcy_mass_flux_water[_qp]*_grad_test[_i][_qp]*_u[_qp];
 }
 
 Real
 ConcreteThermalConvection::computeQpJacobian()
 {
-  return _cw[_qp] * _darcy_moisture_flux[_qp] * _test[_i][_qp] * _grad_phi[_j][_qp];
+  return _cw[_qp] * _Dh[_qp] * _grad_rh[_qp] * _test[_i][_qp] * _grad_phi[_j][_qp];
+  // return
+  // -_specific_heat_water[_qp]*_darcy_mass_flux_water[_qp]*_grad_test[_i][_qp]*_phi[_j][_qp];
```
Comment (bwspenc) [inline src/kernels/ConcreteThermalConvection.C:49]: Should we delete these comments (at the bottom of all of these functions)?

**Comment by bwspenc** [comment]
As a follow-on to this in a separate PR, could you please look into removing `_darcy_moisture_flux` from `PorousMediaBase`.  Maybe that should be part of a larger effort to also rename that class to something that makes more sense to indicate that it is for concrete.
